version: '3.9'

services:
  db:
    image: postgres:16
    container_name: test-n-bet-db
    restart: always
    environment:
      POSTGRES_USER: team_user
      POSTGRES_PASSWORD: tajneheslo
      POSTGRES_DB: test_n_bet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
